# -*- coding: utf-8 -*-
"""LAB 01

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tt8Nbh_MNQsU-L9cy2LELzColLvlLulH
"""

def input_courses(DS, AI, DB, IS):
    pass
def input_cr_hs(cr1, cr2, cr3, cr4):
    pass
def input_obtained_marks(course1, course2, course3, course4):
    pass

def input_courses(DS, AI, DB, IS):
    courses = [DS, AI, DB, IS]
    return courses


def input_cr_hs(cr1, cr2, cr3, cr4):
    credit_hours = [cr1, cr2, cr3, cr4]
    return credit_hours


def input_obtained_marks(course1, course2, course3, course4):
    marks = [course1, course2, course3, course4]
    return marks

def marks_to_gp(marks):
    if marks >= 85:
        return 4.0
    elif marks >= 80:
        return 3.7
    elif marks >= 75:
        return 3.3
    elif marks >= 70:
        return 3.0
    elif marks >= 65:
        return 2.7
    elif marks >= 60:
        return 2.3
    elif marks >= 55:
        return 2.0
    elif marks >= 50:
        return 1.7
    else:
        return 0.0
courses = ["DS", "AI", "DB", "IS"]
credit_hours = [3, 4, 2, 2]
marks = [76, 56, 99, 79]

total_points = 0
total_credits = sum(credit_hours)

for i in range(len(marks)):
    gp = marks_to_gp(marks[i])
    total_points += gp * credit_hours[i]

gpa = total_points / total_credits
print("GPA:", round(gpa, 2))

prev_gpa = 2.80
prev_cr_hours = 11

current_gpa = 2.96
current_cr_hours = 11

cgpa = ((prev_gpa * prev_cr_hours) + (current_gpa * current_cr_hours)) / (prev_cr_hours + current_cr_hours)

print("CGPA:", round(cgpa, 2))



courses = input_courses("DS", "AI", "DB", "IS")
credit_hours = input_cr_hs(3, 4, 2, 2)
marks = input_obtained_marks(76, 56, 99, 79)

print("Courses:", courses)
print("Credit Hours:", credit_hours)
print("Obtained Marks:", marks)
print("Total Marks:", sum(marks))