# -*- coding: utf-8 -*-
"""clean climate data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b8d_GWiETPt0a7ODIFoNrQ3WhZHhn3jU

**ETL Flow**

**ETL Process** — Climate Change & Weather Data Warehouse

 3 Major phases:

**E** → Extract
**T** → Transform
**L** → Load
"""

import pandas as pd

df = pd.read_csv(
    'Beginner_Climate_Change_Dataset_20_Features_1200_Rows.csv'
)

print(df.head())
print(df.info())
print(df.describe())

"""Step 1 — **Missing Values Check**"""

print(df.isnull().sum())
print(df.dtypes)

"""STEP 2 — **Duplicate Records Remove**"""

df = df.drop_duplicates()

numeric_cols = [
    'global_avg_temperature',
    'temperature_anomaly',
    'max_temperature',
    'min_temperature',
    'sea_surface_temperature',
    'predicted_temperature_2050',
    'co2_concentration_ppm',
    'annual_rainfall_mm',
    'air_quality_index'
]

df[numeric_cols] = df[numeric_cols].fillna(df[numeric_cols].mean())

"""STEP 3 — **Correct Data Types**"""

df['year'] = df['year'].astype(int)

"""STEP 4 — **Handle Missing Values**                                
Numerical columns fill with mean
"""

numeric_cols = [
    'global_avg_temperature',
    'temperature_anomaly',
    'max_temperature',
    'min_temperature',
    'co2_concentration_ppm',
    'annual_rainfall_mm',
    'sea_level_rise_mm',
    'sea_surface_temperature',
    'heatwave_days',
    'drought_index',
    'flood_events_count',
    'forest_cover_percent',
    'deforestation_rate',
    'fossil_fuel_consumption',
    'renewable_energy_share',
    'air_quality_index',
    'predicted_temperature_2050',
    'climate_risk_index'
]

for col in numeric_cols:
    df[col] = df[col].fillna(df[col].mean())

"""STEP 5 — **Country Name Standardization**"""

df['country'] = df['country'].str.strip()

"""STEP 6 — **Add Continent Column**"""

!pip install pycountry-convert

import pycountry_convert as pc

def get_continent(country_name):
    try:
        country_alpha2 = pc.country_name_to_country_alpha2(
            country_name
        )

        continent_code = pc.country_alpha2_to_continent_code(
            country_alpha2
        )

        return pc.convert_continent_code_to_continent_name(
            continent_code
        )

    except:
        return 'Unknown'

df['continent'] = df['country'].apply(get_continent)

"""STEP 7 — **Feature Engineering**

A. Temperature Range
"""

df['temperature_range'] = (
    df['max_temperature']
    - df['min_temperature']
)

"""B. Climate Severity Score


.
"""

df['climate_severity_score'] = (
    df['temperature_anomaly']
    + df['sea_level_rise_mm']
    + df['heatwave_days']
    + df['drought_index']
) / 4

"""C. Renewable Dependency Ratio



.
"""

df['renewable_dependency_ratio'] = (
    df['renewable_energy_share']
    /
    (
        df['renewable_energy_share']
        +
        df['fossil_fuel_consumption']
    )
)

"""STEP 8 — **Climate Risk Category**"""

def classify_risk(risk):

    if risk < 30:
        return 'Low Risk'

    elif risk < 60:
        return 'Moderate Risk'

    else:
        return 'High Risk'

df['risk_category'] = (
    df['climate_risk_index']
    .apply(classify_risk)
)

"""STEP 9 —**Final Null Check**"""

print(df.isnull().sum())

"""STEP 10 — **Save Clean Dataset**"""

df.to_csv(
    'Clean_Climate_Data.csv',
    index=False
)

print("Clean dataset saved successfully.")